### PR TITLE
Bump html-pipeline dependency?

### PR DESCRIPTION
**Pull request by gjtorikian**
Version 2.x has been out for a while, so I wonder if there's interest in bumping this.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Absolutely. The main goal is to stay inline with development at GitHub, so let's do it! Thanks!

**Comment by gjtorikian** [comment]
Damn, that was quick. Thanks Dan!

**Comment by mojavelinux** [comment]
Keepin' it movin! :dash:

**Comment by gjtorikian** [comment]
Could a version bump head on out to RubyGems? :heart:

**Comment by mojavelinux** [comment]
Certainly!

Btw, Asciidoctor 1.5.3 is going to be released in ~ 48-hours (fingers crossed). I'm wrapping up the final pull request and preparing release notes.

**Comment by gjtorikian** [comment]
Wink wink, I got you. We'll try to get it on GitHub in a sane amount of time.

**Comment by mojavelinux** [comment]
Super! 1.5.3 is now available.

I'll push out a new version of the filter by the start of the week.

**Comment by mojavelinux** [comment]
It's released! Let me know if you have any trouble with it.

**Pull request merged**
